update script autoSymbolicLink

diff --git a/project1/autoSymbolicLink b/project1/autoSymbolicLink
--- a/project1/autoSymbolicLink
+++ b/project1/autoSymbolicLink
@@ -1,54 +1,81 @@
 #!/bin/bash
 
 
-checkingFile(){
-        # check if the starter files is already exist 
-        # return 1 if doesnt exist
-        if [[ -e './2420-as2-starting-files' ]];then
-            echo 'starting files is exist'
-            return 0 
-        else
-            return 1
-        fi
+username=$1
+homeDir=/home/$username
+starter=$homeDir/2420-as2-starting-files
 
-}
-
-
-clone_dir(){
-
-    checkingFile # running checking
-    status=$? # get the return value and put it to status 
-
+check_username_exists(){
+    #   task: checks if the username entered by the user already exists in the passwd file or not.
+    #   parameter: username($1)
+    #   return: 0,1
     
-    # if the directory is not exist ( status = 1) it clone the starter files
-    if [[ status -eq 1 ]];then 
-        echo clonning....
-        git clone https://gitlab.com/cit2420/2420-as2-starting-files.git
-    fi
+    #   explanation
+    #   the function looping through the list of username in passwd, it check if the name that user enter is match to any username in passwd file
+    #   if it find any match then return 0  (real user)
+    #   if it not find any match then return 1 (user not exist)
+    
+
+
+    local username=$1 # get the user name from positional argument 1 and make it local, since we dont want other function to be able to use the username
+
+    usedUserName=$(cut -d: -f1 /etc/passwd ) # Get the list of all usernames in the passwd file by use command cut and delimeter = :, with -f1 to get the first field (index 0) which is user name then assign it to usedUserName variable
+    usedUserName=(${usedUserName[0]}) # make string to array
+    
+    # Loop over existing usernames(usedUserName). If the name provided by the user matches any of them, return 0 , this will check if username that user enter match any existing username 
+    for name in ${usedUserName[@]}; do # starting loop by loop over usedUserName
+        if [[ $name == $username ]]; then # check if enter name is equal to the name in used name 
+            echo "found user"
+            return 0  # return 0, mean the username that user enter is exist in passwd file (real user)
+        fi
+    done
+    echo "invalid user"
+    exit 1 # if it finish loop without find any match then exit 1 (stop script), mean that the user name that user enter is not exist
+    
 }
+
+
+DeleteHomeFile(){
+    #   task: delete the file bin .bashrc .config if it exist
+    #   parameter: 
+    #   return: 
+        
+    Link=(bin .bashrc .config) # defind the list of file name that is going to be delete ( becuase these file name will be use as symbolic link target)
+
+    for file in ${Link[@]};do # start loop each file in Link
+        if [[ -e "$homeDir/$file" ]];then # check if the file is exist in home directory 
+            rm -r $homeDir/$file && echo delete $file successfully || echo unable to delete the file # if the file is exist then delete it
+        fi
+        
+    done
+
+
+}
+
 
 
 createSymbolicLink(){
+    #   task: create symbolic links from the starter file (2420-as2-starting-files)
+    #   parameter: 
+    #   return: 
+
+    sourceFile=("bin" "home/bashrc" "config") # defind the file name to use as the source of symbolic link
+
+    for f in {0..2};do # loop through the number of the file that need to create as a symbolic link (3)
+        #in each loop create a symbolic link from starterfile/sourcefile to the homedirectory/linkname
+        ln -s $starter/${sourceFile[$f]} ${homeDir}/${Link[$f]} && echo create symbolic link successfully || echo fail to create symbolic link
+
+    done
+
     
-
-
-    
-    mv $HOME/bin/* $HOME/assignment2/linuxAssignment2/project1/2420-as2-starting-files/bin 
-    # move any files in the home bin to the starter bin
-
-    if [[ -e $HOME/bin ]];then 
-        rm -rf $HOME/bin
-    fi
-    #remove bin folder in home directory 
-    
-    ln -s $HOME/assignment2/linuxAssignment2/project1/2420-as2-starting-files/bin $HOME/bin
-    #create a symbolic link from home/bin to /bin in the starter files
-
-
-
-
 }
 
+
+
+# call the function to check the argument and create symbolic link
+
+check_username_exists $1
+DeleteHomeFile
 createSymbolicLink
 
 
diff --git a/project2/userset b/project2/userset
--- a/project2/userset
+++ b/project2/userset
@@ -10,45 +10,24 @@ fi
 
 
 
-
-check_username_valid_chars(){
-    #   task: check if the username that user provide is usable (no special charecter)
-    #   parameter: username($1)
-    #   return: 0,1
-    
-    
-    #   explanation
-    #   the function loop through the list of special charecter and check if the username contain any of them
-    #
-    local username=$1 # get the user name from positional argument 1 and make it local, since we dont want other function to be able to use the username
-    
-    #defind list of special charecter
-    special_char=("!" "@" "#" "$" "%" "^" "&" "*" "(" ")" "-" "_" "=" "+" "{" "}" ";" ":" "/" "?" "." ">") 
-
-    for char in ${special_char[@]}; do # loop each special charecter name it char
-        if [[ $username == *"$char"* ]]; then # check if username contain any special charecter
-            echo "Username can't contain special characters."
-            return 1 # return true once it found any spcial chareter in username
-        fi
-    done
-    
-    return 0 # if it finish the loop without find any special charecter then return 0
-}
-
-
 check_username_exists(){
     #   task: checks if the username entered by the user already exists in the passwd file or not.
     #   parameter: username($1)
     #   return: 0,1
     
     #   explanation
-    # If the username already exists, return 1 and echo "This username has already been used."
+    #   the function looping through the list of username in passwd, it check if the name that user enter is match to any username in passwd file
+    #   if it find any match then return 1 (fail)
+    #   if it not find any match then return 0 (sucess)
+    
+
+
     local username=$1 # get the user name from positional argument 1 and make it local, since we dont want other function to be able to use the username
 
-    usedUserName=$(cut -d: -f1 /etc/passwd ) # Get the list of all usernames in the passwd file by cutting from :, and get the first field (index 0) which equal to user name
+    usedUserName=$(cut -d: -f1 /etc/passwd ) # Get the list of all usernames in the passwd file by use command cut and delimeter = :, with -f1 to get the first field (index 0) which is user name then assign it to usedUserName variable
     usedUserName=(${usedUserName[0]}) # make string to array
     
-    # Loop over existing usernames(usedUserName) in the passwd file. If the name provided by the user matches one of them, return 1 and echo "This username has already been used.", this will check if username that user enter match any existign username 
+    # Loop over existing usernames(usedUserName). If the name provided by the user matches any of them, return 1 and echo "This username has already been used.", this will check if username that user enter match any existing username 
     for name in ${usedUserName[@]}; do # starting loop by loop over usedUserName
         if [[ $name == $username ]]; then # check if enter name is equal to the name in used name 
             echo "This username has already been used."
@@ -74,7 +53,6 @@ check_shellpath(){
         shellList=$(tail -n +4 /etc/shells | cat ) # Get the available shells (ignore the first 3 lines, thus using tail -n+4) and save them in the variable shellList
         shellList=(${shellList[0]}) # make string to araay
         
-        # Check if the user shell path is available by comparing it to the variable shellList
         for shell in ${shellList[@]}; do # looping over the available shell list
             if [[ $shell == $userShell ]]; then # if one of the shell is match with shell path that user enter then return 0
                 return 0
@@ -93,17 +71,20 @@ assign_user_id(){
     #  Parameter:
     #  Return: userID
     
-    
+    # explanation 
     # It checks if the ID is taken or not. If not, it assigns it to the new user.
+    # by looping from number 1000 (i=1000), it check if the number is match with any id in passwd file
+    # if i is not match (equal) to any id in the passwd file then assign it to user other wise increate i by one and loop again until it find the id (not match in passwd file)
+
     
-    # usedUserID stores the values of user IDs already created, by using cut from : and selecting the third position to get the ID number in the passwd file.
+    # usedUserID stores the values of user IDs already created, by using cut from :(-d:) and selecting the third position(-f3) to get the ID number in the passwd file.
     usedUserID=$(cut -d ":" -f3 /etc/passwd )    # usedUserID stores a list of existing user IDs
     
     #make string to array
     usedUserID=(${usedUserID[0]})
-    local userID
+    local userID # declare variable userID
 
-    # the following code will try to assign the user id by finding the available id (id is not in used)
+    # the following code will try to assign the user id by finding the available id (id is not in usedID)
 
     local i=1000 # defind variable i, i will be use as user id when the condition met (start from 1000 because userID)
     while [[ -z $userID ]];do # start the loop by check if the userID is still empty (not assign yet)
@@ -136,8 +117,8 @@ assign_group_id(){
     
     ## the following code Check if userID can be used as group ID (usually group ID matches userID)
 
-    usedGroupID=$(cut -d ":" -f3 /etc/group) # get all of the group id by using cut from : and get the third field in /etc/group file
-    if [[ ${usedGroupID[@]} =~  $userID ]]; then # If userID is already in group ID (meaning group ID is already taken)
+    usedGroupID=$(cut -d ":" -f3 /etc/group) # get all of the group id by using cut from : (-d:)and get the third field (-f3) in /etc/group file
+    if [[ ${usedGroupID[@]} =~  $userID ]]; then # If userID is already in group ID (meaning group ID is already taken and cant use userID as group id), then it will try to find new group id for usergroup
         echo "User ID is not available to use as group ID." >&2 
         echo "Assigning new group ID.......">&2
         declare groupid # delclear an empty variable name group id
@@ -147,13 +128,13 @@ assign_group_id(){
         # Find an available group ID. If the ID is available (not in used IDs), it assigns it to the variable groupid. (this step is similar to find user id but now we find id in /etc/group)
         # the following code will try to assign the group id by finding the available id (id is not in used)
 
-        local i=1000 # defind variable i, i will be use as group id when the condition met (start from 1000 because userID)
+        local i=1000 # defind variable i, i will be use as group id when the condition met (start from 1000)
         while [[ -z $groupid ]];do # start the loop by check if the groupid is still empty (not assign yet)
             if [[ $i -eq 65534 ]];then # first check i is not 65534 since it need to preserve as nobody group
                 continue # if the condition met then skip the rest of the loop and start the new loop
             fi
 
-            if [[ ! ${usedGroupID[@]} =~ $i ]];then # check if i is not in usedID (availble to use for the new user)
+            if [[ ! ${usedGroupID[@]} =~ $i ]];then # check if i is not in usedGroupID (availble to use for the new user)
                 groupid=$i # if the i is not in used id then assign to ther UserID
                 break # stop the loop
             fi
@@ -161,7 +142,7 @@ assign_group_id(){
             ((i++)) # at the end of each loop, increase the value of i by 1
 
         done
-        echo $groupid
+        echo $groupid #return groupid
 
     else # this mean user id is not in group id which mean it available to be use as group id
         echo $userID #return userID, which will use as group id
@@ -175,14 +156,13 @@ mkhomeDir(){
     #   Parameter: userHome($1)
     #   Return: 0,1
     
-    local userHome=$1
+    local userHome=$1 #defind the userHome variable from positional argument 1 
     
-    ### Create a home directory using mkdir
+    # Create a home directory using mkdir
     if mkdir $userHome; then 
         echo "Home directory created successfully."
         
     else
-        echo "An error occurred."
         return 1
     fi
     
@@ -206,12 +186,13 @@ create_user(){
     #   Return: 0,1
     
     #   explanation
-    # 0. check the argument that given to this function by using function 
+    # 0. check the argument that given to this function by using checking functions
     # 1. assign variables (username, userShell, userHome, userID, groupid) and make it global variable
     # 2. make home directory for user (from the function mkhomeDir)
     # 3. append user data to passwd file 
     # 4. append user data to group file
     # 5. change ownership of home directory
+    # 6. assign password to the user
     
     
     # 0. checking argument
@@ -220,9 +201,9 @@ create_user(){
     # if all of the checking function run successfully, it will assign the arguments to the variables (global)
 
 
-    checking_func=(check_username_valid_chars check_username_exists check_shellpath) #defind checking function 
-    checking_arguments=($1 $1 $3) # defind the argument that will be pass down to the function
-    for i in {0..2}; do #start loop 3 time (checking_func size)
+    checking_func=(check_username_exists check_shellpath) #defind checking function 
+    checking_arguments=($1 $3) # defind the argument that will be pass down to the function
+    for i in {0..1}; do #start loop 2 time (checking_func size)
         ${checking_func[$i]} ${checking_arguments[$i]} #run the checking function with argument 
         if [[ $? -eq 1 ]]; then # check if any exit code (also return ) is equal to one
             return 1 # if any function return one then stop script and return 1 (fail)
@@ -242,7 +223,7 @@ create_user(){
     
     # 1.1 assign shell path if not provided
     # Check if the user provided a shell path. If not, set the shell to the default: /bin/bash
-    if [[ -z $3 ]]; then # check if positionl argument is empty 
+    if [[ -z $3 ]]; then # check if positionl argument (3) is empty 
         echo "No shell path provided, setting shell to default: /bin/bash" 
         userShell="/bin/bash" # assign the default value (/bin/bash) to the usershell variable
     fi
@@ -278,10 +259,23 @@ create_user(){
     chown -R $username:$username $userHome || { echo "failed to change ownership of home directory" >&2; return 1; }
     
     # 6. assign password to the user
-    passwd $username || { echo "failed to assign password" >&2; return 1; }
-    
+    # check if the password that user given is correct (sucessfuly run passwd command)
+    # if not then ask for password again (run passwd again)
 
-    #done, now printing out all of the user information
+    enterpassword=false # set the variable enterpassword, this will use to check the loop condition
+    while [[ $enterpassword == false ]];do # start the while loop by use the enterpassword variable = false
+        if passwd $username; then # run the passwd command with user name
+            enterpassword=true # if the passwd command return 0 (run sucessfuly) then change the enterpassword to true (this will stop the loop)
+        else
+            echo please enter password again! # if the passwd command return 1 (fail) then continue running the loop (run passwd again until the command passwd return 0 and print to the user
+        continue
+        fi
+    done 
+
+
+
+
+    #done, now printing out all of the user information from global variable
     echo "------- user details -------"
     echo username: $username
     echo comment : $userInfo
@@ -302,61 +296,68 @@ adduserGroup(){
     #   Parameter: groupname
     #   Return: 0,1
     
-    # This function is used with the -g flag to add a user to a specific group
+    # explaination 
+    # the function addusergroup will add the user to the group that user given by check the group name in /etc/group file and if it exist then it will create data in can be append to the group file, if not given then it stop the function
+    # and if the group that user enter is not exist then it will return 1 and stop the function
     
     
-    # Get the arguments and put them in variables entergroup (the group the user entered) and username (the user to be added to the group)
-
+    # assign the positional argument the variable enter group
     local entergroup=($@)
 
     
-    # If the argument is null, then return 0; it won’t add any user to the group or run the code below
-   
+    # If the argument(entergroup) is null, then return 0; it won’t add any user to the group or run the code below
     if [[ -z $entergroup ]]; then
         return 0
     fi
-    groupNames=$(cut -d: -f1 /etc/group ) # Get the list of group names in /etc/group
-    groupNames=(${groupNames[0]}) # Adjust index in the list
-    
-    for group in ${entergroup[@]};do
 
-        if [[ ! ${groupNames[@]} =~ $group ]]; then # Check if the group entered exists in the file
+   
+    groupNames=$(cut -d: -f1 /etc/group ) #Get all group names in /etc/group by using cut from ":" and get the first field from the group file (ex groupname:x:id after cut -> groupname)
+    groupNames=(${groupNames[0]}) # make string to list
+    
+    for group in ${entergroup[@]};do # looping through list of the group that user enter 
+
+        if [[ ! ${groupNames[@]} =~ $group ]]; then # Check if the group entered exists in the file by using =~
             echo "The $group group you’re trying to add the user to does not exist!" # If it doesn’t exist, echo to inform the user
-            continue
+            continue # skip the rest and start a new loop
 
             
         else # If the group exists, it will try to add the user to the /etc/group file (code below)
             
-            # Get the list of group names by using awk
+            # Get the group name in the file /etc/group by using awk
             # Separate each position by -F:, -v to pass the value to awk
-            # Check if the first field on any line matches the entergroup
+            # Check if the first field on any line matches the group
+            # if the group match any existing group then it assign in to variable group match
             groupmatch=$(awk -F: -v group="$group" '$1 == group {print}' /etc/group)
             
-            # Get the line number of the group by using grep -n to get the line number, then cut to get the line number only
+            # grep with -n groupmatch to get the line and line number of group match, then cut ":" and select first field to get only the line number
             numberline=$(grep -n $groupmatch /etc/group | cut -d: -f1 )
     
             
-            # Check if the group the user is trying to add has group members or not. If there are members, add a comma before the username.
+            # get the group member of the group that user trying to add by using grep and select the last field 
             groupmember=$(grep -n $groupmatch /etc/group | cut -d: -f5 )
-            
+
+            # Check if the group that user is trying to add has group members or not. If there are members, add a comma before the username.
             if [[ -z $groupmember ]]; then # If the group has no members
                 
-                sed -i "${numberline}s/$/$username/" /etc/group # Insert the username at the end of the line (line $number line)
+                sed -i "${numberline}s/$/$username/" /etc/group # Insert the username at the end of the line 
             else
+                # else will trigger if there are member in the group 
                 sed -i "${numberline}s/$/,$username/" /etc/group # Insert the username with a comma before the name at the end of the line
             fi
-            
-            echo "User added to group ${group} successfully!" # Add a check to verify that it worked, if necessary
+
+            echo "User added to group ${group} successfully!" 
         fi
     done
     return 0
 }
 
-while getopts "s:m:g:hpc:" opt; do
+while getopts "s:m:g:hpc:" opt; do # using getopts and while loop to get the flag when script is call 
+    # assign the argument of each flag to each variable 
+    # make varible_flag to true when the flag is call
     case $opt in
         m)
             m_flag=true
-            enterName=${OPTARG}
+            enterName=${OPTARG} 
         ;;
         s)
             s_flag=true
@@ -368,10 +369,10 @@ while getopts "s:m:g:hpc:" opt; do
         ;;
         c)
             c_flag=true
-            
             enterComment=${OPTARG}
-            ;;
+        ;;
         ?)
+            echo invalid flag 
         ;;
     esac
 done
@@ -380,24 +381,24 @@ done
 if [[ -z $@ ]]; then
     echo "Usage: sudo userSet [OPTION].....
     -m <username> create user
-    -s <shellPath> assign shell path
-    -g <groupname> add user to the existing group
-    -c <comment> to add comment
+    -s <shellPath> assign shell path (optional) 
+    -g <groupname> add user to the existing group (optional)
+    -c <comment> to add comment (optional)
     For more information: -h"
-elif [[ ! $m_flag ]]; then
-    echo "This script requires -m <user name>"
-elif [[ $m_flag && $g_flag ]]; then
-    # give the default the comment and shell, since this two argument are not require
-    
+elif [[ ! $m_flag ]]; then # check if script is call without m flag
+    echo "This script requires -m <user name>" # echo to user that no flag provide
+elif [[ $m_flag && $g_flag ]]; then # check if the flag m and g are call, then the script should call function create user and add user group
     create_user "$enterName" "$enterComment" "$enterShell"
-    if [[ $? -eq 0 ]]; then
+    if [[ $? -eq 0 ]]; then # check if exit code of create user is 0 then run the add user group 
       
         echo adding group...
         adduserGroup "$enterGroup"
     fi
 else
-    create_user "$enterName" "$enterComment" "$enterShell"
+    create_user "$enterName" "$enterComment" "$enterShell" # if there is flag m then run create user (other flag is optional)
 fi
+
+### note : the flag m is away require but the other flag can be empty (argumet can be empty) since the function will handle it. 
 
 # Links
 # https://www.baeldung.com/linux/find-available-shells#:~:text=To%20find%20available%20shells%20on,shells%20installed%20on%20the%20system.
